### ISSUE TITLE
Adding Contributing.md file 

### ISSUE THREAD

**Issue by PravinPadalkar78** [MCPI-Revival/Ninecraft#2]
I would like to add contributing.md file to your repository.
Please assign this issue to me #hacktoberfest

**Comment by nobody5050** [comment]
If you create a pull request and we like it we’ll give it the hacktoberfest-approved tag

**Comment by nobody5050** [comment]
We don’t need to assign an issue to you for you to be able to open a pull request.

**Comment by PravinPadalkar78** [comment]
Ok fine then

**Comment by PravinPadalkar78** [comment]
I had sent the PR , can u please check
